### ISSUE TITLE
Direct sonos support (without HA in between).

### ISSUE THREAD

**Issue by vandalon** [xaviml/controllerx#126]
Hi, 

first of all, thanks for the great appdaemon app 👍 

I think it would be great to have the option to control sonos directly without HA in between. This will make controlling volume more smoothly (I think) :)

Cheers,
Joris

**Comment by xaviml** [comment]
Hi @vandalon,

Thank you for the suggestion. Do you mean to reach the Sonos API (if that is how is integrated with HA) directly through ControllerX? This is what at first, I wanted to achieve, this is why all communication is done through HA because HA provides an API that will work for any device integrated with HA, so I wouldn't need to maintain different integrations. I am considering to have [communication directly through MQTT](https://github.com/xaviml/controllerx/issues/118), but I have no plan to integrate other ways, specially if they are tight to a specific device.

On a side note, I use ControllerX with my Symfonisk controller to control the volume for my Google Home mini and TV, and it works smoothly for me. You can check out this videos:
- https://twitter.com/xaviml93/status/1278000379444240390
- https://twitter.com/xaviml93/status/1216124464901115905

If you share your configuration and you tell me about your setup (which controller you have, which integration, where is the coordinator, etc), I might be able to help you with your smooth problems.

I will leave this ticket close, but we can communicate in here if you have any problems with the smoothness.

Cheers,
Xavi M.

**Comment by vandalon** [comment]
Turned out my controller was just bad. I got 2 new ones and they work better :)

I figured that direct communication with sonos would lower latency and thus improve performance/experience.

The cpu usage of controllerX (or maybe just appdaemon) on a raspberry pi 4 is very high so I am now testing to achieve the same thing with home assistants own automations via the repeat + while options. This seems to work ok.
