### ISSUE TITLE
[BUG]WXKG01LM (Aqara) dimming (by holding) not working

### ISSUE THREAD

**Issue by timvdhoorn** [xaviml/controllerx#129]
# Bug report
WXKG01LM (Aqara) dimming (by holding) not working
## Description
When holding the button dimming is not working. the other options; single, dubble etc works as expected.

## Additional information

* Devices involved:
WXKG01LM (Aqara) as controller
Philips Hue bulbs as lights
  * ...
* Integration: z2m
* AppDaemon version: 0.3.0
* ControllerX version: 3.4.0
* Home Assistant Core version: 0.114.4

## AppDaemon app configuration

apps.yaml
Woonkamer_controller:
  module: controllerx
  class: WXKG01LMLightController
  controller: sensor.s_woonkamerw_action
  integration: z2m
  light: light.woonkamer_lights

## Logs

Log of appdaemon: real life behaivor: first click to turn on, then hold to dim (which is not working)
2020-09-05 08:54:21.412168 INFO Woonkamer_controller: 🎮 ControllerX v3.4.0
2020-09-05 09:00:27.221019 INFO Woonkamer_controller: 🎮 Button event triggered: `single`
2020-09-05 09:00:27.225235 INFO Woonkamer_controller: 🏃 Running `toggle` now
2020-09-05 09:00:27.232801 INFO Woonkamer_controller: 🤖 Service: light.toggle
2020-09-05 09:00:27.241497 INFO Woonkamer_controller:   - entity_id: light.woonkamer_lights

## Additional Context

**Comment by xaviml** [comment]
Hi @timvdhoom,

This could be happening because the controller is also exposing a sensor called "sensor.s_woonkamerw_click" where the "hold" and "release" are fired. If that is correct, then your configuration should be like:

```yaml
Woonkamer_controller:
  module: controllerx
  class: WXKG01LMLightController
  controller:
    - sensor.s_woonkamerw_action
    - sensor.s_woonkamerw_click
  integration: z2m
  light: light.woonkamer_lights
```

If this is not the problem, could you share the z2m logs when:
- pressing once
- pressing twice
- pressing 3 times
- pressing 4 times
- pressing more than 4
- Holding
- Releasing

Cheers,
Xavi M.

**Comment by htvekov** [comment]
Hi' @timvdhoorn & @xaviml 

The WXKG01LM is working perfectly here with ControllerX. Both via standard z2m and mqtt integration (see settings below)
The Xiaomi buttons are almost identical in their device naming, so it can be somewhat confuzing.
It  is the round version (actually Mija series, not Aqara) you have right ?

Don't really understand why you have `action` as payload key ?
This is the second time in two days I've seen z2m configurations with payload keys that differ from what I have ?
What zigbee2mqtt version are you on ?

The WXKG01LM has only one sensor exposed (action), where as the WXKG12LM (and 11LM as well I believe) have actions split into two sensors. Action sensor for hold, shake and release and click sensor for single & double clik.
So unless z2m herdsman converters have changed since v1.14.2 then it should work ?

**And hey presto, it HAS changed... 😖**
Just had a quick glance at the [z2m documentation](https://www.zigbee2mqtt.io/devices/WXKG01LM.html) and the `click` key for this device has been deprecated.
Unless you have added `legacy: false` to this device in z2m configuration.yaml then `click` action should still be exposed.

I have to check z2m documentation and see how many of my devices have revised payload keys etc. 😒

Here's my app configuration and log with zigbee2mqtt 1.14.4 where WXKG01LM is controlling my office lights:

```yaml
office4_controller:
  module: controllerx
  class: WXKG01LMLightController
  
  controller: 'zigbee2mqtt/Doorbell Utilitydoor/click'
  integration: mqtt
  #controller: sensor.0x00158d00035a660f_click #Xiaomi round remote
  #integration: z2m
  
  automatic_steps: 8
  delay: 400
  smooth_power_on: true
  light: light.0xec1bbdfffed45c3b_light
```


```
zigbee2mqtt:info  2020-09-05 19:20:45: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":118,"click":"single"}'
zigbee2mqtt:info  2020-09-05 19:20:45: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":118,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:45: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'single'
zigbee2mqtt:info  2020-09-05 19:20:45: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"OFF","color_temp":370,"brightness":0,"update_available":false,"linkquality":107}'


zigbee2mqtt:info  2020-09-05 19:20:46: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":"double"}'
zigbee2mqtt:info  2020-09-05 19:20:46: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:46: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'double'
zigbee2mqtt:info  2020-09-05 19:20:47: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":254,"update_available":false,"linkquality":107}'


zigbee2mqtt:info  2020-09-05 19:20:48: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":118,"click":"triple"}'
zigbee2mqtt:info  2020-09-05 19:20:48: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":118,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:48: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'triple'
zigbee2mqtt:info  2020-09-05 19:20:49: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":1,"update_available":false,"linkquality":107}'


zigbee2mqtt:info  2020-09-05 19:20:51: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":"quadruple"}'
zigbee2mqtt:info  2020-09-05 19:20:51: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:51: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'quadruple'
zigbee2mqtt:info  2020-09-05 19:20:51: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":127,"update_available":false,"linkquality":107}'


zigbee2mqtt:info  2020-09-05 19:20:53: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":"many"}'
zigbee2mqtt:info  2020-09-05 19:20:53: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:53: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'many'


zigbee2mqtt:info  2020-09-05 19:20:56: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":"long"}'
zigbee2mqtt:info  2020-09-05 19:20:56: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:56: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'long'
zigbee2mqtt:info  2020-09-05 19:20:56: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":157,"update_available":false,"linkquality":107}'
zigbee2mqtt:info  2020-09-05 19:20:57: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":189,"update_available":false,"linkquality":107}'
zigbee2mqtt:info  2020-09-05 19:20:57: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":221,"update_available":false,"linkquality":107}'
zigbee2mqtt:info  2020-09-05 19:20:58: MQTT publish: topic 'zigbee2mqtt/Office ceiling', payload '{"state":"ON","color_temp":370,"brightness":253,"update_available":false,"linkquality":107}'


zigbee2mqtt:info  2020-09-05 19:20:58: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":"long_release","duration":1747}'
zigbee2mqtt:info  2020-09-05 19:20:58: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor', payload '{"battery":100,"voltage":3022,"linkquality":115,"click":""}'
zigbee2mqtt:info  2020-09-05 19:20:58: MQTT publish: topic 'zigbee2mqtt/Doorbell Utilitydoor/click', payload 'long_release'
```

Ciao !

**Comment by htvekov** [comment]
FYI 

Found this from Koenkk in another thread: 

**Koenkk commented 13 days ago
In Zigbee2MQTT 1.14.3 automations based on click are broken (Koenkk/zigbee2mqtt#4168). Just fixed this in the latest dev branch (Koenkk/zigbee2mqtt#4168 (comment))thread**

I think I'll stay on z2m 1.14.2 for a while until newest stable v1.14.4 has proven ok...

Ciao !

**Comment by timvdhoorn** [comment]
Hi all, thanks for the replies. It happened that I needed to add both click as action as @xaviml mentioned.

Thanks!

**Comment by htvekov** [comment]
No worries, @timvdhoorn  ! 😎

As I've mentioned earlier, just be aware that the `click` event key has been deprecated and will at some point in future be removed completely.

Xavi will probably have to revise code with additional default event keys for quite a few devices.
Otherwise issues like this will keep popping up over the next many months. And depending on time users originally have integrated their z2m  devices in HA and version of z2m installed, some will have deprecated `click`- others `action` event keys.
Not the smartest z2m deprecation move I've seen... 🤔😒
