### ISSUE TITLE
[FEATURE REQUEST] Merging custom action mapping with default

### ISSUE THREAD

**Issue by kroimon** [xaviml/controllerx#135]
# Feature Request

### Is your feature request related to a problem?

Modifying the action of a single button requires duplicating all default mappings into the config file, which results in unnecessarily long configuration files.

### Describe the solution / feature you'd like

I would like to have a way to (automatically) merge a custom mapping with the default one, so you only have to specify what you want to change from the default mapping.

I don't think it is a good idea to always merge a custom mapping with the default one as this makes it hard to disable default actions. Any suggestions on how to still optionally implement this? Maybe another config item called `merge_default_mapping` that defaults to false to mimic the old behavior, and can be set to true for the proposed behavior?

**Comment by xaviml** [comment]
Hi kroimon :)

This is a good idea. I have been asked before for this and I found myself in this situation with my own setup. As you say, it is not good to change the behaviour for two reasons:
- Breakng changes. This would break lots of configuration.
- Sometimes you want to hard replace the default mapping.

I agree with the solution you are proposing, adding a new key that will work the same as the `mapping`, but instead of hard replace the mapping, it would replace the defined actions over the default one. Instead of calling it `merge_default_mapping`, I would call it just `merge_mapping`. If you are interested in adding a PR for this, the related code for this is in `apps/controllerx/core/cx_core/controller.py:L57`.

Regards,
Xavi M.

**Comment by xaviml** [comment]
A new attribute `merge_mapping` has been added to ControllerX v4.0.0b1. I have tested this myself, but I would appreciate if this gets tested by more people. Thanks :)

**Comment by xaviml** [comment]
This has been added to ControllerX v4.0.0.
