### ISSUE TITLE
E1744 (Symfonisk Sound Controller) mapping not working

### ISSUE THREAD

**Issue by Veeedka** [xaviml/controllerx#162]
I've found that the output of the Symfonisk controllers doesn't seem to match up with the displayed outputs shown in the ikea.py file - The outputs of the controller are as follows: 

"rotate_left" (twist left) instead of "brightness_move_down"
"rotate_right" (twist right) instead of "brightness_move_up"
"rotate_stop" (stop twisting) instead of "brightness_stop"
"play_pause" (click) instead of "toggle"
"skip_forward" (double click) intead of "brightness_step_up"
"skip_backward" (triple click) instead of "brightness_step_down"

I've confirmed these via the zigbee2mqtt add-in, however changing these names in ikea.py does not show any output in the log file of the Appdaemon docker container. 

Am I missing something here?

**Comment by xaviml** [comment]
Hi @Veeedka,

This is because the current mapping for this controller is for when the `legacy: false` is added in the `devices.yaml`. You can read more about this in the [FAQ]() #8. Also if you are using the sensor for this controller I would recommend you to check FAQ#9 as well.

Regarding changing the python file (ikea.py), you can change it, but then the AppDaemon needs to be restarted to refresh the changes. However, this is something I do not recommend you since if you upgrade version, then you will lose those changes. Instead, you can add a custom mapping with `mapping` attribute, you can add in there any actions you want with YAML configuration.

Let me know if you have any questions about this, happy to help.

Regards,
Xavi M.

**Comment by Veeedka** [comment]
Thank you, @xaviml ! You're awesome :)
