### ISSUE TITLE
Properly emulate color_temp for xy_color lights that don't support color temperature

### ISSUE THREAD

**Issue by wafliron** [xaviml/controllerx#171]
# Feature Request

### Is your feature request related to a problem?

I have a number of Ikea Tradfri Bulb E27 bulbs (Ikea ID 104.086.16) that natively support RGB colour but don't natively support setting a colour temperature.

Using color_wheel: color_temp_wheel, ControllerX is able to emulate colour temperature support for these bulbs.

With this setting in place, click_color_down / click_color_up / hold_color_down / hold_color_up behave as expected, with the light cycling through the emulated white spectrum "colour space". 

However, as far as I'm aware, there is no way to set them straight to full / min / half colour _temperature_. The actions on_full_color_temp / on_min_color_temp / set_half_color_temp (as well as the equivalent "white_value" actions) do nothing when applied to these bulbs.

### Describe the solution / feature you'd like

It would be great to be able to set a RGB-only bulb using color_wheel: color_temp_wheel straight to full / min / half (emulated) colour temp.

### Describe alternatives you've considered

Accept I can't set this type of bulb straight to full / min / half colour temperature :-)

### Additional context

N/A, but please let me know if any further info / clarification is needed.

**Comment by xaviml** [comment]
Hi @wafliron,

Thank you for raising this. The current behaviour is expected, because the "emulated" color_temp is done though `color_wheel`, so it is expected as a color_wheel to be circular and not have a min a max value.

What you are requesting is emulate the color_temp for xy_color lights that do not support colour temperature. My opinion is that this should be implemented on HA level since they have more control of this than I do in ControllerX. I am not saying this is not possible, just that if it was done in HA core, it will be more useful than if I implemented myself for this addon.

I will keep this open anyway, but it won't be added any time soon.

Regards,
Xavi M.

**Comment by wafliron** [comment]
Hi @xaviml,

Thanks for the detailed response. 

Agree 100% it would be better for HA itself (or the underlying ZigBee library used by ZHA) to handle this. Unfortunately there doesn't seem to be much interest - a couple of feature requests have been opened over the past 12-24 months, but they've all been closed with minimal activity (or in some cases, minimal activity outside of some discussion). Which I must admit is what lead to me asking about it here :-)

But, point taken, and fair enough - hopefully the HA / ZHA team will get around to implementing this at some point!

**Comment by xaviml** [comment]
Hi @wafliron,

I have assessed this with the code changes it would imply, and I would need to change some of the core things to implement it, so I have decided not to implement it for now.

Related to this, I saw that HA added the option to emulate color temp, but it works if you send a request, but it will not add a `color_temp` attribute. If that attribute was added, then everything requested originally in here would work. You can try it yourself, but you will see that the `click` and `hold` actions will not work.

I will close this ticket, but I will open it again if this gets picked up.

Regards,
Xavi M.
