### ISSUE TITLE
[NEW DEVICE] Muller Licht Tint Remote z2m integration

### ISSUE THREAD

**Issue by tomekpap** [xaviml/controllerx#176]
# New Device Support

## Device Information

* Device Model: [ MLI404011 ]
* Device Description: [ eg. Muller Licht Tint Remote MLI404011]
* Device Manufacturer: [ eg. Muller Licht Tint ]

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

* `'off' / 'on': Sent alternately when Power button is clicked
* 'color_wheel': Sent when color wheel is clicked, any of 4 buttons beneath it, in the payload there is additionally color information in payload, e.g.: "action_color":{"x":0.644,"y":0.35} recognized as attribute in HA, there are 36 different set of color values in the color wheel, I can provide all if necessary, but I think it would be enough to just increase the saturation with some xy to hs converter
* 'color_temp': Sent when either of light temperature buttons is clicked or hold, in the payload there is additionally 'action_color_temperature' attribute sending mireds in range 153 - 370 (when clicking) and 153-555 when holding buttons (main action is sent with each change every second or so

Some actions need no explanation
* `brightness_down_click'
* 'brightness_up_click'
* 'brightness_down_hold'
* 'brightness_down_release'
* 'brightness_up_hold'
* 'brightness_up_release'

There is also 6 scene actions 'scene_#' numbered on the remote: 
3 1 2
6 4 5

#### Notes

With every action the device sends 'action_group' attribute, allowing to control different lights.
values of it are: 16388, 16389, 16390. When all light groups is selected no messages reach the network.
I made custom mqtt sensor to make us of it feature and control different light groups, but it would be much cleaner to be able to set it up just in controllerx

**Comment by grostim** [comment]
I am also interested in this controller.

I would like to clarify that the action_group are not fixed. The values 16388,16389,16490 are te defaults, but they may change depending on the group binded to the remote.
See my addedum to the docs here:
https://github.com/Koenkk/zigbee2mqtt.io/pull/456

**Comment by xaviml** [comment]
Hi both,

The only button I can give support easily are:
- on/off
- brightness_up_click
- brightness_down_hold
- brightness_down_release
- brightness_up_hold
- brightness_up_release

The rest require reading the payload which is not possible if the integration of z2m is from listening to the sensor from HA entity. I would need to redesign the way that z2m is integrated, so we could pass data from payload easily to the actions.

This means that I will for the moment integrate this controller with the same functionality as deconz but without the color_temp since z2m sends the same action for both buttons.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Support for z2m has been added to ControllerX [v4.2.0](https://github.com/xaviml/controllerx/releases/tag/v4.2.0).
