### ISSUE TITLE
Aqara Opple 6 button - no events

### ISSUE THREAD

**Issue by ChristofferStr** [xaviml/controllerx#219]
# Question

No events is showing up with "Aqara Opple 6 button device"
I need the device ID

## Additional information

* Devices involved:
  * Model: WXCJKG13LM (Aqara)
* Integration: deconz
* AppDaemon version: latest
* ControllerX version: latest
* HACS version (if installed from there): latest
* Home Assistant Core version: latest

**Comment by ChristofferStr** [comment]
Is there anyone who knows how i can fix it

**Comment by xaviml** [comment]
Hi @ChristofferStr,

I can help you with this issue. However, you need to understand that this project is developed and maintained by someone in its own spare time, so responding time will not be as desired sometimes. Also, if you want to be helped, the more information you can provide the better. The template you filled in also asks for AppDaemon logs, and ControllerX configuration. This would help a lot to get a context of the problem.

What do you mean by `I need the device ID`? If what you need is to get your device ID, [here](https://xaviml.github.io/controllerx/others/extract-controller-id#deconz) you have the documentation on how to extract it. If you are asking something else, could you please rephrase your problem and add AppDaemon logs and your ControllerX config?

Regards,
Xavi M.

**Comment by ChristofferStr** [comment]
Hi.
Thank you so very much. Yes i know and im very glad for the help. You helped me before with the "Aqara double rocker". When the project didnt supprt it. Im on another acocunt with new email.
thx again.

Yes it is the device_id i need. But when i listen for "deconz_event" nothing happens when i trigger the opple remote. It works with other remotes, ikea and double rocker. 
So i cant see the "device id".

You understand what i mean?

thanks thanks

**Comment by xaviml** [comment]
Hi @ChristofferStr,

I see, so the problem is that you don't see events popping up when listening for `deconz_event` and pressing your controller. I would recommend you checking the following:
- Phoscon app to see if the controller is properly set up.
- Check the deCONZ integration from `Configuration > Integrations > deCONZ`. Do you see your controller there?

Let me know what you see and I might be able to help you further.

Regards,
Xavi M.

**Comment by ChristofferStr** [comment]
i think it is properly set up. i can use the controller. i have set upp to dim and toggle lights.
Yes i see the controller there, the name there is:
lumi.remote.b686opcn01

**Comment by xaviml** [comment]
Hi @ChristofferStr,

![Screenshot from 2021-01-09 23-16-09](https://user-images.githubusercontent.com/3974003/104109687-d418c380-52d0-11eb-808d-0e44aa202248.png)

If you click on the device from the Device list when clicking on `Configuration > Integrations > deCONZ`, you will see the name on top. In my case, the name is `hue-dimmer-switch`. The `lumi.remote.b686opcn01` I believe is the model.

However, if you don't see the controller popping up in Developer Tools when listening for deconz_event, you will not be able to use it with ControllerX, since it is listening for that event.

Regards,
Xavi M.

**Comment by ChristofferStr** [comment]
thx for the answers.
Do you have any idea why its not popping up in the "event"? and do you have any idea how i can fix it?

thx

**Comment by xaviml** [comment]
The responsible to send the deconz_event is the deCONZ integration, but if you already see the controller in there and everything looks fine, what I would do is restart Home Assistant.

Just to make sure, are you listening for the event in here?
![Screenshot from 2021-01-09 23-28-14](https://user-images.githubusercontent.com/3974003/104109871-6c637800-52d2-11eb-9e43-a7fb6866f78e.png)

Regards,
Xavi M.

**Comment by ChristofferStr** [comment]
Yes. thats were im listening :)

testing a reboot now

**Comment by ChristofferStr** [comment]
Now it comes up. The reboot did it, thought i tried it before though. But thx. hope it works now.

thx thx

**Comment by xaviml** [comment]
It's incredible how a simple reboot has fixed many problems in life. I'm glad it is working now :+1: 

Let me know if you have more questions, but I will keep this ticket close.
