### ISSUE TITLE
WXKG01LM (Aqara) controller via deconz

### ISSUE THREAD

**Issue by lasse9000** [xaviml/controllerx#245]
I think there is something wrong with the WXKG01LM (Aqara) controller via deconz
https://xaviml.github.io/controllerx/controllers/WXKG01LM

Mine is sending 1001 and 1000 then I hold the button and 1003 then I relase the button. The event 1000 also sendt with 1 click 1002
So 1000 should not be used
1001 for hold and
1003 for released

**Comment by xaviml** [comment]
Hi @lasse9000,

You are totally right. I added this controller via a request (#143), and I blindly trusted the mapping (which I normally do, since I do not have the controller with me). However, I do know that deconz uses X000 for initial press (and it should not be used as you indicate), X001 for hold, X002 for short release, X003 long release.

I just released a new patch version with this fix (v4.5.1). It will be released in 5-10 minutes since this comment is sent.

Regards,
Xavi M.
