### ISSUE TITLE
[NEW DEVICE] New Philips Hue Dimmer (with "Hue" Logo on Off Button)

### ISSUE THREAD

**Issue by capullo** [xaviml/controllerx#264]
# New Device Support

## Device Information

- Device Model: Hue Dimmer 2.Gen
- Device Description: Hue Dimmer with "Hue" Logo on the Off-Button
- Device Manufacturer: Philips

## Integrations
I only have z2m, so i tested there
Same Mapping like the HueDimmerController.
"-" must be replaced with "_" for actions.
1.Gen Hue Dimmer: "on-hold-release"
new 2.Gen Hue Dimmer: "on_hold_release"

**Comment by xaviml** [comment]
Hi @capullo,

Thank you for opening this ticket. I will be adding this controller for the next release.
Device to be added: https://www.zigbee2mqtt.io/devices/929002398602.html

As you said, all the actions are the same, but replaced with "_" (snake case instead of kebab case). In addition, I see in z2m documentation that the new deevice also has the following actions:
* on_press_release
* off_press_release
* up_press_release
* down_press_release

They are not much relevant, but they make more sense to press actions that the "press" ones.

I will keep you updated.

Regards,
Xavi M.

**Comment by xaviml** [comment]
This device has been added to [ControllerX v4.9.0](https://github.com/xaviml/controllerx/releases/tag/v4.9.0).
