### ISSUE TITLE
[QUESTION] BrightnessUp/Down Speed ?

### ISSUE THREAD

**Issue by racha** [xaviml/controllerx#390]
# Question

I've been digging for a bit now and I can't find a way to change the speed of the dimming (delay between actions while using HOLD) any way of changing that ? It's quite slow. I understand I can use less steps but I want more control with more steps but then it takes ages to go through all the steps...

test_app:
  module: controllerx
  class: E1744LightController
  controller: sensor.0x5c0272fffe298ec1_action
  light: light.table_light
  integration: z2m
  mapping:
    brightness_move_down:
      action: hold
      attribute: brightness
      direction: down
      steps: 20
    brightness_move_up:
      action: hold
      attribute: brightness
      direction: up
      steps: 20
    brightness_stop:
      action: release

## Additional information

* Devices involved:
  * Model: E1744LightController
  * ...
* Integration: Choose from z2m
* AppDaemon version: AppDaemon 4 Current version: 0.7.1
* ControllerX version: v4.16.0
* HACS version (if installed from there): 1.17.2
* Home Assistant Core version: core-2021.11.4

**Comment by xaviml** [comment]
Hi @racha,

The attributes you are looking for are:
- `automatic_steps`: Number of steps to go from min to max when smoothing. If the value is 2 with one click you will set the light to 50% and with another one to 100%.
- `delay`: Delay in milliseconds that takes between sending the instructions to the light (for the smooth functionality). Note that if leaving to 0, you might get uncommon behavior.

First, since you are using E1744, I recommend you to switch to MQTT (read more in [FAQ#9](https://xaviml.github.io/controllerx/faq)). This will allow you to have a much faster response from the controller. Secondly, the values for those 2 attribute I recommend are:
- `automatic_steps`: 10
- `delay`: 250

This should speed your current brightness to double since the default for delay is 500 for that controller. You can lower it down to 200 if it works for you. If you need to keep a higher delay, then I recommend you lowering down the steps to make it less granular, hence, it will go faster because less steps will need to be made.

Regards,
Xavi M.

**Comment by xaviml** [comment]
I will close this ticket for now. If something else needs to be discussed, please open a new ticket.
