### ISSUE TITLE
[NEW DEVICE] add EnOcean PTM 215Z support

### ISSUE THREAD

**Issue by akentner** [xaviml/controllerx#420]
# New Device Support

## Device Information

- Device Model: PTM 215Z
- Device Description: Pushbutton transmitter module
- Device Manufacturer: EnOcean (White-label | Easyfit by EnOcean EWSxZ, Trio2sys, Senic Friends of Hue (Gira))

This device has 4 buttons:

Button | Position
-- | --
A0 | top left
A1 | bottom left
B0 | top right
B1 | bottom right

In my case (Senic Friends of Hue), the device comes with 2 types of cover plates: single and double. So you can choose between one or two "switches".

#### Actions

Action | Event
-- | -- | 
`recall_scene_0` | on A0 pressed
`recall_scene_4` | on A0 released
`recall_scene_1` | on A1 pressed
`recall_scene_5` | on A1 released
`recall_scene_3` | on B0 pressed
`recall_scene_7` | on B0 released
`recall_scene_2` | on B0 pressed
`recall_scene_6` | on B0 released
`press_2_of_2` | on A0+B0 pressed
`release_2_of_2` | on A0+B0 released
`press_1_of_2` | on A1+B1 pressed
`release_1_of_2` | on A1+B1 released

`pressed` is while the button is down, `release` when button comes up. On a single "click", you get both events

Since you can use 1 or 2 lamps on the device, I suggest as default mapping for a single plate:

A0+B0 clicked-> light on
A1+B1 clicked -> light off
A0+B0 hold-> brightness up
A1+B1 hold-> brightness down

#### Notes

See: https://www.zigbee2mqtt.io/devices/PTM_215Z.html

I investigated the MQTT stream and found some differences to the z2m documentaion of the device.
There are other actions documented on z2m page:

- `press_1`
- `release_1`
- `press_2` 
- `release_2`
- `press_3`
- `release_3`
- `press_4`
- `release_4`
- `press_1_and_3`
- `release_1_and_3`
- `press_2_and_4`
- `release_2_and_4`
- `press_energy_bar`

But while I'm listening on the `zigbee2mqtt/<deviceId>/action` topic, I see other actions: `recall_scene_[0-7]`, `press_[1|2]_of_2` and `release_[1|2]_of_2`. I used this for the actions section above

**Comment by xaviml** [comment]
Hi @akentner ,

The release actions is fired when the buttons are released after being held?

Also when is the "press_or_release_all" fired?

Is there any specific default mapping for this controller?

Regards,
Xavi M.

**Comment by akentner** [comment]
Hi Xavi, 
I did som "listening" on the MQTT stream and found some differences. I updated the task above. I hope that makes it clearer.

Regards
Alex

**Comment by akentner** [comment]
I also updated the device, I have the PTM 215Z not PTM 215ZE

**Comment by Skorfulose** [comment]
After another bit of research, the Niko91004 integration *could* be renamed/generalized to PTM215Z I guess. The issue is with [a breaking change in zigbee2mqtt 1.21.2](https://github.com/Koenkk/zigbee2mqtt/issues/9028).
I am still on z2m 1.18.1, latest version available as Home Assistant add-on.

As per @kris10an, the Niko91004 indeed originally reported the recall_scene_x via zigbee2mqtt, too.
https://github.com/xaviml/controllerx/issues/364

Not sure how to go about this now. The upstream issue was closed because stale. But I guess it should still be fixed there? If the device actually supports different actions for hold and release, why would you "hide" it on the application level?

**Comment by kris10an** [comment]
I believe the Niko 91004 is identical to the Enocean PTM215Z, or PTM216Z. It's even labelled as such, see picture. FCC ID is 215Z, a bit harder to see if the model is 215Z or 216Z.

![IMG_7694 (2) - Copy](https://user-images.githubusercontent.com/17658084/152153267-3a15c601-f2f7-4cda-875f-0662d3ec59e5.jpg)

 The [PTM216Z manual](https://www.enocean.com/wp-content/uploads/downloads-produkte/en/products/enocean_modules_24ghz/ptm-216z/user-manual-pdf/PTM_216Z_User_Manual_v1.4.pdf) chapter 3.3.1 seems to indicate that only push and release events are sent. Earlier I believed it did also send hold action, but not so sure any more.

So one option for hold actions may be to implement a timed delay at some level. The release event is only sent when the button is released. I'm for now using an automation with some 1 second wait delays to get hold functionality, discussed [here](https://community.home-assistant.io/t/no-actions-received-with-niko-dimmer-switch-green-power-and-zigbee2mqtt/335027/7?u=kris10an).  Also saw this [blueprint](https://gist.github.com/nickknissen/cecd1d6260068f886c565427059c3a0a) using delays.

If I remember correctly from looking into this a while back, I believe deconz has the hold/dim action implemented. When I previously used the hue bridge I was also able to set actions on button held.

**Comment by Skorfulose** [comment]
Oh dear, I found that my z2m HA add-on was stuck on the older 1.18.1 for a reason...
After moving from the obviously outdated add-on repo https://github.com/danielwelch/hassio-zigbee2mqtt to the current https://github.com/zigbee2mqtt/hassio-zigbee2mqtt, I am running 1.23.0.

I can now confirm that z2m publishes the changed actions for my Senic switch. I now see press_x and release_x instead of recall_scene_. Personally I find that naming more intuitive. But still no hold action. I assume there never has been, via z2m. Only via deconz.

@akentner: Can you verify your z2m version? Is it 1.21.2 or above?
@xaviml: Should we generalize the Niko91004 and rename it to PTM215x? And then add the corresponding z2m-specific actions?

press_1
release_1
press_2
release_2
press_3
release_3
press_4
release_4
press_1_and_3
release_1_and_3
press_2_and_4
release_2_and_4
press_energy_bar

Any button press will trigger both actions (press_x and release_x), no matter if it is a short press or a long press (aka. hold).

**Comment by akentner** [comment]
Indeed, I also made the same mistake: I used the outdated repo of Daniel Welch.

And I confirm, now I also get the same actions @Skorfulose described.

@xaviml Is it possible to get the delta time between two actions and "fake" additional events:

- 0-500ms => `press_x_short`, 
- at 500ms and no release =>`press_x_long` a.k.a. `hold_x`
- release after `press_x_short` => `release_x_short`
- release after `press_x_long` => `release_x_long`

(Or better naming)

**Comment by xaviml** [comment]
Hi all,

Sorry for the delay on this issue. This is the summary of what needs to be done if I understood correctly:
- Rename `Niko91004LightController` to `PTM215XLightController`
- Add Z2M to `PTM215XLightController` with the mapping from @Skorfulose https://github.com/xaviml/controllerx/issues/420#issuecomment-1027959558

@akentner:
> Is it possible to get the delta time between two actions and "fake" additional events:

I am afraid this is not possible as of now. I will add the controller with default actions (clicks will be toggles, and release will be release). Then, it can be configured with `mapping` in the configuration.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi all,

I released [ControllerX v4.19.0b1](https://github.com/xaviml/controllerx/releases/tag/v4.19.0b1) with this new controller added. If not problems are raised, I will release v4.19.0.

Regards,
Xavi M.

**Comment by akentner** [comment]
Hi Xavi,

thank you for your work. I'll update my config and test it, as soon as my infrastructure is online again (another sad story).

Regards, Alex

**Comment by xaviml** [comment]
Thank you @akentner, and I hope you get your infrastructure back :)

**Comment by xaviml** [comment]
This device has been added in [ControllerX v4.19.0](https://github.com/xaviml/controllerx/releases/tag/v4.19.0).
