### ISSUE TITLE
[FEATURE REQUEST] Support long/short press for hue dimmer switch

### ISSUE THREAD

**Issue by chbndrhnns** [xaviml/controllerx#53]
# Feature Request

### Is your feature request related to a problem?

Yes. According to [1], deconz reports long and short presses for that switch. I would like to make use of that in my automations.

[1] https://www.home-assistant.io/integrations/deconz/#remote-control-devices

**Comment by xaviml** [comment]
Hi @chbndrhnns 

You can find the events for the press, hold and release action for this controller in [here](https://xaviml.github.io/controllerx/controllers/hue-dimmer-switch). If you add this to ControllerX by default, you will be able to change color (xy or temperature) when holding "I" or "O" and brightness hold or pressing the other 2 buttons.

Is this what you were referring to? Otherwise, could you specify your issue?

**Comment by chbndrhnns** [comment]
Hey, 

according to the linked page, deconz provides an additional event code that is currently not captured in in controllerx:

XXX2 | Button short release (not implemented)
XXX3 | Button long release (implemented)

How difficult would it be to distinguish between long and short press?

**Comment by xaviml** [comment]
Ah okay, so the issue is that short **release** is not implemented. The default behaviour of the Hue Dimmer switch does not use the short release since there is no use case for this. Whatever you do in the short release, it will be always right after the short press is fired. Which use case you think would be convenient for the default behaviour of this controller? 

Nonetheless, you can use the  XXX2 (short release) with [custom controller](https://xaviml.github.io/controllerx/others/custom-controllers) if you are looking for more specific/advanced use case.

Do you have a problem with the short press, hold (or long press) and long release?

**Comment by xaviml** [comment]
Also, I will add this event to the documentation. Thank you for spotting it @chbndrhnns !

**Comment by chbndrhnns** [comment]
Here is a snapshot of 1) pressing a button and releasing it quickly and 2) pressing a button and releasing it after ~ 2 seconds. I removed `origin` and `context` for brevity.

<details>
<summary>Click to toggle snapshot</summary>

1)

```
Event 1
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1002
    },
    "time_fired": "2020-03-10T07:39:30.932886+00:00",
}

Event 0
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1000
    },
    "time_fired": "2020-03-10T07:39:30.804852+00:00",
}

```

2)

```
Event 3
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1003
    },
    "time_fired": "2020-03-10T07:40:45.837950+00:00",
}

Event 2
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1001
    },
    "time_fired": "2020-03-10T07:40:45.517918+00:00",
}

Event 1
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1001
    },
    "time_fired": "2020-03-10T07:40:44.765677+00:00",
}

Event 0
{
    "event_type": "deconz_event",
    "data": {
        "id": "dimmer_kitchen",
        "unique_id": "00:17:88:01:04:ac:c7:3b",
        "event": 1000
    },
    "time_fired": "2020-03-10T07:40:43.917427+00:00",
}
```

</details>

What I see:
- each press creates a `X000` event
- quick release creates `X002` event
- long press creates `X001` while pressed and `X003` after release

I think the default for controllerx could be the `1002`, like a short press.

I will try @sreknob 's [suggestion](https://github.com/xaviml/controllerx/issues/51#issuecomment-596540869) for the mapping, though.

**Comment by xaviml** [comment]
Hi @chbndrhnns 

Since it is a press, there is almost no time difference between the short press and short release (0.1s difference in your events). So short will stay with 1000 event (when clicked and not when released) for the default behaviour of the controller. However, you can tweak that with [custom controllers](https://xaviml.github.io/controllerx/others/custom-controllers).

May I know why you prefer the click on the short release and not the short press? I still do not know what is the feature request or issue related to this ticket.

Thank you,
Xavi M.

**Comment by chbndrhnns** [comment]
I shortly learned how to use the `CallServiceController` to customize the behavior. Doing it in that way would be fine for me.

My use case is:
- short press switches a light on
- long press switches a light on for a defined duration

**Comment by xaviml** [comment]
Okay, then yes, "custom controllers" is what you are looking for, but you can use the 1000 event for the short press instead of 1002. One comes after the other one. I will leave this closed then.

Thank you @chbndrhnns !
