### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Debug1Bug** [xaviml/controllerx#552]
# Question

Is it possible to get the WXCJKG11LM controller working with either Deconz or ZHA? Currently it's only supported by Z2M?

## Additional information

- Devices involved:
  - Model: WXCJKG11LMLightController
- Integration: deconz | zha
- AppDaemon version: [ 0.9.3 ]
- ControllerX version: [ 4.22.0 ]
- HACS version (if installed from there): [ 1.26.2 ]
- Home Assistant Core version: [ 2022.8.7 ]

## AppDaemon app configuration

```yaml
(optional) Insert your appdaemon app configuration here (apps.yaml content).
Insert only the configuration relative to the controllerx app you're asking the question for.
```

## Logs

```text
(optional) Add relevant AppDaemon / Home Assistant logs which could help answering the question.
```

## Additional Context

There are three of these types of buttons supported by ControllerX (2, 4 and 6 buttons) for some reason, the two button on is only supported on Z2M, the 4 button one by both Z2M and ZHA and the 6 button one by Z2M, ZHA and Deconz. I have all three types of buttons nut only ZHA and Deconz, so I would like for a way to use the 2 button version, if at all possible. Thanks in advance, and thanks for a truly great integration.

**Comment by xaviml** [comment]
Hi @Debug1Bug ,

I started ControllerX by giving support to some IKEA controllers since they were the ones I had. However, I created ControllerX to be flexible and be able to add different controllers. The reason this device you mention is not supported by deCONZ and ZHA is because I do not have this controller (and integrations) and no ones has reported to me the events that each button triggers.

If you would like support for this controller and you have one of them, you can fill in the "New device support" form when [creating an issue](https://github.com/xaviml/controllerx/issues/new/choose). You will need to indicate which events are shown for the integration you would like to be added, and which button was pressed or action was done. Then, I will add the configuration into ControllerX for anyone to consume.

Regards,
Xavi M.

**Comment by Debug1Bug** [comment]
Hi @xaviml,
Thank you for a job well done. It truly is a great app.
I have filled out the form for Deconz. I don't have one of these buttons connected via ZHA just yet, but if I do, I will submit information for that as well.
Have a nice day.

**Comment by xaviml** [comment]
Thank you @Debug1Bug , I will close this ticket for now. We will be adding the support through the other one.
