### ISSUE TITLE
[QUESTION] ZHA Philips929002398602 not supported

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#604]
Is there a specific reason the Philips 929002398602 does not have ZHA support?

**Comment by xaviml** [comment]
Hi @inertia666 ,

The reason is that no one has requested its support. If you have this device integrated with ZHA, you can open an issue with the "New device" template.

In any case, someone has alresdy created a PR to support this devicr with ZHA, but it is marked as WIP, and I have not heard back from the author.

https://github.com/xaviml/controllerx/pull/580

Regards,
Xavi M.

**Comment by inertia666** [comment]
Ok thanks for the info!
