### ISSUE TITLE
[FEATURE REQUEST] Support long press on middle button for E1524/E1810 

### ISSUE THREAD

**Issue by chbndrhnns** [xaviml/controllerx#61]
# Feature Request

### Is your feature request related to a problem?

yes

### Describe the solution / feature you'd like

The switch emits an event if you press the main button for around 4 to 5 seconds. Its id is `1001`. Could we add support for that, as well?

### Describe alternatives you've considered

None

**Comment by chbndrhnns** [comment]
I tested the event and it works, it's just not documented.

**Comment by xaviml** [comment]
Hi @chbndrhnns,

I gave support for the middle button for z2m, but I did not add the event for deconz. I will add this for the next release. The functionality will be to sync the light(s) to maximum brightness and 3700K of color or white colour. However, you must know that the controller also sends a toggle action (`1002`) when holding the middle button. So it will fire first `1002` and then `1001`. This means that before firing the long hold action, it will toggle the light first.

Furthermore, you can use the `1001` if you want with [Custom Controllers](https://xaviml.github.io/controllerx/others/custom-controllers).

Thanks for opening the feature request.

**Comment by chbndrhnns** [comment]
Interesting, because the event 1001 works as expected even for deconz. It triggers the action after 5 seconds of pressing the button.

**Comment by xaviml** [comment]
If you hold the middle button, don't you see `1002` and then after 5 seconds  `1001`?

**Comment by chbndrhnns** [comment]
You are right, I also see this behaviour. I was just playing with `1001` so I did not notice the`1002`.

**Comment by xaviml** [comment]
That is right. Every time you want to fire an  action with `1001`  then, `1002` will be fired. However, the default behaviour of the controller is that no matter if the light is on or off the `1001` it will put the light in full brightness and 3700K, but it will turn on or turn off the light before that. Since the end-user will know what the long hold does, it doesn't matter that toggles the light first. You can see more about this in #54 .

Also, we decided to go this path because is the default behaviour of the controller when paired with IKEA hub and ControllerX will always try to copy the behaviour the user had with the original hub. This is the [video](https://www.youtube.com/watch?v=cq1VXrdLc00&feature=youtu.be) of the original behaviour.

**Comment by xaviml** [comment]
I added `1001` in the docs now as well that in the E1810Controller for the deCONZ integration. It will be deployed in the next release.
