### ISSUE TITLE
[QUESTION] Use iolloi LED Dimmer to control multiple lights?

### ISSUE THREAD

**Issue by gregorsarrazin** [xaviml/controllerx#618]
# Question
I have a iolloi Zigbee LED Dimmer (https://zigbee.blakadder.com/iolloi_ID-EU20FW09.html) connected to deconz. I can control the device through deconz or home assistant without any problems but it's just changing the non smart lightbulb physically connected to the dimmer. The dimmer itself gets recognized as a lightbulb in deconz and supports on/off and brightness. Therefore, there is no deconz_event fired when I use the dimmer.

Instead of just controlling one non-smart LED lightbulb connected directly to the dimmer, I would like to configure this dimmer so that it controlls a light group from home assistant. Is that possible with controllerx?

My idea: controllerx gets configured so that it keeps other devices in sync with this single dimmer/lightbulb. If my dimmer/lightbulb gets turned on, controllerx turns on the configured light group. If my dimmer/lightbulb changes brightness, controllerx does sync these changes with the configured light group.

Is it possible to configure controllerx so that it does sync state changes of one lightbulb with another light bulb/group?

## Additional information

- Devices involved:
  - One deconz light (that is a physically rotary dimmer) synching a HA lightgroup (or just another light)
- Integration: deconz
- AppDaemon version: ? Currently using AppDeamon AddOn v0.9.3
- ControllerX version: v4.24.0
- HACS version (if installed from there): [ eg. v0.21.5 ]
- Home Assistant Core version: 2022.10.5

**Comment by xaviml** [comment]
Hi @gregorsarrazin ,

I am afraid this is not something you can do with ControllerX. ControllerX is thought to control a light (e.g. iolloi Zigbee LED Dimmer) with a controller (e.g. Philips Hue Dimmer, or any other from [this list](https://xaviml.github.io/controllerx/controllers/)). If the iolloi Zigbee LED Dimmer fires the `deconz_event`, then you could configure this with ControllerX, otherwise, it is not possible. You could partially do this with the [`state` integration](https://xaviml.github.io/controllerx/start/integrations/#state), but you would miss brightness feature you are looking for.

This is not something that could be added in ControllerX since deCONZ is not sending this information through deconz event, so ControllerX cannot read this data.

The option you have is to configure this with Home Assistant configuration. You would need:
- An automation that gets triggered when the state of your light changes (on, off), and then as an action you turn on/off the group of lights. You can split this in 2 automations maybe.
- Another automations that gets triggered when there are changes in the brightness attribute of your light entity, and then as an action, you would need to change the light group brightness to the same as your main light.

Regards,
Xavi M.
