### ISSUE TITLE
Tradfri Open/Close Remote

### ISSUE THREAD

**Issue by hwikene** [xaviml/controllerx#71]
# New Device Support

## Device Information

* Device Model: E1766 
* Device Description: Tradfri Open/Close Remote 
* Device Manufacturer: IKEA 

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

* `button_z_press (up)`: 1002
* `button_z_hold (up)`: 1003
* `button_z_press (down)`: 2002
* `button_z_hold (down)`: 2003

#### Notes

(Optional) Additional notes for the integration, eg. known bugs, issues or limitations of the device for the specified integration.

**Comment by xaviml** [comment]
Hi @hwikene 

I just released ControllerX v2.6.0 with this controller: https://xaviml.github.io/controllerx/controllers/E1766

I also added the Cover Controller, so you are able to use this controller for lights, switches, and covers.

Let me know how it works :)

**Comment by guymaurier** [comment]
Hi @xaviml,

I'm facing an issue with the E1766CoverController and its Click down → Close/Stop cover command. A first click will make the cover go down, however a second click will not stop it.
The Click up → Open/Stop cover works as expected, first click will open the cover, a second click will make it stop.

I'm using the E1766 switch along with IKEA's Fyrtur cover. Both are configured through deconz.

I've doubled checked that the switch is correctly sending out the events (click) as well as ensuring the cover is sending out state changes (closing with position state).

Could you please help in investigating this situation?
Thanks

**Comment by xaviml** [comment]
Hi @guymaurier,

Could you send the logs from AppDaemon for when that happens as well as the supported_features from your cover (you can extract that from Developer Tools)? I will need to see what is happening under the hoods.

Cheers,
Xavi M.

**Comment by trevorbenyack** [comment]
Hi, I just got my Fyrtur blinds working with deConz and ControllerX.  It works... kind of. The issue is with the hold & release events. The way they are presented in the documentation doesn’t look correct. This remote behaves a tad differently than the on/off remote. I’ve listed below how the events should work:

1002 -> Doubles as both short and long press for opening the blinds, there’s no distinction.
1003 -> This is a release event. Only happens when the open button is long pressed. Should stop the blinds opening after a long press.
2002 -> Doubles as both short and long press for closing the blinds, there’s no distinction.
2003 -> This is a release event. Only happens when the close button is long pressed. Should stop the blinds closing after a long press.

As it is working now, the holding and releasing of either the close or open button does not stop the blind from closing/opening. I’m not super familiar with the underpinnings of Home Assistant, but I would think this is how they would work in an automation: 

1002 -> cover.open_cover
1003 -> cover.stop_cover
2002 -> cover.close_clover
2004 -> cover.stop_cover

Hope this helps. If there’s any other information I can help with, please let me know. Thank you for all your work!

**Comment by xaviml** [comment]
Hi @trevorbenyack,

I was not aware of this behaviour for this controller. Right now, the default mapping for `E1766CoverController` for deCONZ is:
- 1002: It opens if it is not moving, it stops if it is moving (opening/closing states)
- 2002: It closes if it is not moving, it stops if it is moving (opening/closing states)

I think this is okay since it allows to toggle the functionality of the clicks depending on the state of the blinds (as long as it supports opening/closing actions, see #199). However, it is missing:
- 1003: Stop cover
- 2003: Stop cover

I will add these 2 new predefined actions to the `E1766CoverController`.

**Comment by xaviml** [comment]
Hi @trevorbenyack,

I added the changes to the dev branch. They will be in the next release, which will happen before next week. In the meantime, you can use the `merge_mapping` attribute to define the behaviour for 1003 and 2003 events.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
The latest changes mentioned in this issue have been deployed in ControllerX [v4.4.0](https://github.com/xaviml/controllerx/releases/tag/v4.4.0).

**Comment by trevorbenyack** [comment]
Thanks for your work on this!
