### ISSUE TITLE
More support ZHA for TuYaERS10TZBVKAA

### ISSUE THREAD

**Issue by OliverDudgeon** [xaviml/controllerx#830]
# Feature Request

### Is your feature request related to a problem?

Full ZHA support for TuYaERS10TZBVKAA

### Describe the solution / feature you'd like

The Zigbee2MQTT support for TuYaERS10TZBVKAA seems much better than ZHA. It would be nice for these to be in parity.

**Comment by xaviml** [comment]
Hi @OliverDudgeon ,

I would need more information to fulfill this request. I recommend you opening the "New device" issue and fill the form. I would need the mapping for all the actions that ZHA supports. If it was not added at first, it probably was because ZHA didn't have the same capabilities as Zigbee2MQTT. This might have change, so I can help you on adding the right mapping you could provide it to me.

Thanks you,
Xavi M.

**Comment by OliverDudgeon** [comment]
How should I got about capturing this? The main thing missing for me is the native `double` action, in #625 only toggle, turn and hold-turn were listed.

**Comment by xaviml** [comment]
Hi @OliverDudgeon ,

Could you create a "New device" issue on GitHub and mention the events that your controller fires in ZHA? If it fires the events you are looking for, we could add them in the default mapping.

Regards,
Xavi M.
