### ISSUE TITLE
[NEW DEVICE] Niko dimmer switch for Hue system

### ISSUE THREAD

**Issue by phdelodder** [xaviml/controllerx#89]
# New Device Support

## Device Information

* Device Model: [ XXX-91004 ] (the XXX is the color code)
* Device Description: [ Niko dimmer switch for Hue system ]
* Device Manufacturer: [ Niko ]
* Device URL: [ https://www.niko.eu/en/article/100-91004 ]

## Integrations

If possible, provide the event mappings for the different actions that can be performed on the controller. Specify the integration.

If you can provide mappings for multiple integrations, copy the section below as many times as needed.

#### Actions

Reference for buttons: https://phoscon.de/en/support#pairing-friends-of-hue-switch

* `button_1_press`:  1000
* `button_1_hold`:  1001
* `button_1_release`:  1002
* `button_1_release_after_hold`:  1003
* `button_2_press`:  2000
* `button_2_hold`:  2001
* `button_2_release`:  2002
* `button_2_release_after_hold`:  2003
* `button_3_press`:  3000
* `button_3_hold`:  3001
* `button_3_release`:  3002
* `button_3_release_after_hold`:  3003
* `button_4_press`:  4000
* `button_4_hold`:  4001
* `button_4_release`:  4002
* `button_4_release_after_hold`:  4003
* `button_1_3_press`:  5000
* `button_1_3_hold`:  5001
* `button_1_3_release`:  5002
* `button_1_3_release_after_hold`:  5003
* `button_2_4_press`:  6000
* `button_2_4_hold`:  6001
* `button_2_4_release`:  6002
* `button_2_4_release_after_hold`:  6003

**Comment by xaviml** [comment]
Hi @phdelodder,

Thank you for the request. This is more than enough to give support to this controller. However, I see this is a very customizable controller, so giving a default behaviour to it might not satisfy your necessities. This seems a perfect controller to use together with [custom controller](https://xaviml.github.io/controllerx/others/custom-controllers) so you can input the mapping of your liking for your own use case.

So I will be adding the documentation for the controller, so you can reference the mapping you just told me and also a default behaviour to control one light (brightness, color, setting brightness to min and max, sync, etc). You can reference the light predefined actions in the custom controller page. I will be telling you shortly which behaviour I will be giving it.

**Comment by xaviml** [comment]
After creating the mapping, I realise that "release" actions XXX2 are not very useful since we already have "release_after_hold" (XXX3). This is the mapping I created:
- Button 1:
  - press: Turn on light(s)
  - hold: Sync light(s)
- Button 2:
  - press: Turn off light(s)
  - hold: Sync light(s)
- Button 3:
  - press: Full brightness
  - hold: Brightness up
- Button 4:
  - press: Min brightness
  - hold: Brightness down
- Button 1_3:
  - press: Full color temp (if supported)
  - hold: Color up (color wheel or color temp)
- Button 2_4:
  - press: Min color temp (if supported)
  - hold: Color down

Again, you will be able to change this behaviour by using custom controllers. If you tell me what is your use case, I will be able to help you with the configuration for it :)

Thanks!

**Comment by xaviml** [comment]
I close this issue since the controller is included on ControllerX v2.8.0
